// src/app/device-control/presentation/components/device-list/device-list.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { TranslatePipe } from '@ngx-translate/core';

import { Device } from '../../../domain/model/device.entity';
import { DeviceCardComponent } from '../device-card/device-card.component';

@Component({
  selector: 'app-device-list',
  standalone: true,
  imports: [DeviceCardComponent, TranslatePipe],
  templateUrl: './device-list.component.html',
  styleUrl: './device-list.component.scss',
})
export class DeviceListComponent {
  @Input({ required: true }) devices: Device[] = [];

  @Output() toggle = new EventEmitter<number>();
  @Output() remove = new EventEmitter<number>();

  trackByDeviceId(index: number, device: Device): number {
    return device.id;
  }
}

@if (devices.length > 0) {
  <section class="device-grid">
    @for (device of devices; track device.id) {
      <app-device-card
        [device]="device"
        (toggle)="toggle.emit($event)"
        (remove)="remove.emit($event)"
      />
    }
  </section>
} @else {
  <article class="empty-state">
    <h3>{{ 'devices.emptyTitle' | translate }}</h3>
    <p>{{ 'devices.emptyContent' | translate }}</p>
  </article>
}

// src/app/device-control/presentation/components/device-list/DeviceList.vue
<template>
  <div class="devices-list">
    <DeviceCard
      v-for="device in devices"
      :key="device.id"
      :device="device"
      @toggle="$emit('toggle', $event)"
      @remove="$emit('remove', $event)"
    />

    <article v-if="devices.length === 0" class="empty-state">
      <h3>{{ t('devices.emptyTitle') }}</h3>
      <p>{{ t('devices.emptyContent') }}</p>
    </article>
  </div>
</template>

<script setup lang="ts">
import { useI18n } from 'vue-i18n';
import type { Device } from '../../../domain/model/device.entity';
import DeviceCard from '../device-card/DeviceCard.vue';

defineProps<{
  devices: Device[];
}>();

defineEmits<{
  toggle: [deviceId: number];
  remove: [deviceId: number];
}>();

const { t } = useI18n();
</script>

<style scoped lang="scss">
.devices-list {
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.empty-state {
  padding: 28px;
  border-radius: 24px;
  background: var(--surface-main);
  border: 1px dashed var(--border-accent);
  color: var(--text-muted);
}

.empty-state h3 {
  margin: 0 0 8px;
  color: var(--text-main);
}

.empty-state p {
  margin: 0;
  color: var(--text-muted);
}
</style>
